/* Generated By:JavaCC: Do not edit this line. FiltersParserConstants.java */
package org.mule.module.magento.filters;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FiltersParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 5;
  /** RegularExpression Id. */
  int BINARY_OP = 6;
  /** RegularExpression Id. */
  int UNARY_OP = 7;
  /** RegularExpression Id. */
  int INDIV = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int IDENTIFIER = 11;
  /** RegularExpression Id. */
  int OPEN_PAR = 12;
  /** RegularExpression Id. */
  int CLOSE_PAR = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\",\"",
    "<BINARY_OP>",
    "<UNARY_OP>",
    "<INDIV>",
    "<NUMBER>",
    "<STRING>",
    "<IDENTIFIER>",
    "\"(\"",
    "\")\"",
  };

}
